### PR TITLE
use size_t for void pointer cast

### PR DESCRIPTION
**Pull request by martell**
As discussed in issue #64

### CODE REVIEW

**Comment by martell** [comment]
Hi @vgvassilev any update on the merge ??

**Comment by vgvassilev** [comment]
@martell Merged, thanks! Could you tell on which platform and compiler was the issue?

**Comment by martell** [comment]
The Platform was windows. Was tested on 2 compilers, gcc and clang with mingw-w64 headers.

**Comment by vgvassilev** [comment]
Thanks, I hope now it is better for your case. I'd be very happy to see mingw support in our .travis.yml so that this never happens again.

**Comment by martell** [comment]
mingw-w64 v4.0 will be released in the few days I will test with that once it is done.
I'd like to report back on how well it works :)

**Pull request merged**
