### PR TITLE
CPT commits

### PR DESCRIPTION
**Pull request by onyb**
Some general improvements to Cling Packaging Tool. This pull request also includes a patch to address #74, but don't consider ```v0.1``` as a stable release.

Once we have a stable version, we can mark it as a new tag (say ```v0.2```), add some relevant release notes to the tag, and then try to minimize dependency on the ```git``` client. This is possible with the new GitHub API, but CPT builds a changelog for Debian packages using ```git``` command-line client at the moment.

### CODE REVIEW

**Comment by onyb** [comment]
**Note:** Travis CI won't pick up the recent changes to CPT unless this PR is merged in. After the merge, the builds should complete successfully (I have disabled the tests for now).

**Comment by vgvassilev** [comment]
Thanks Ani, I will merge and see what happens. Is that okay?

**Comment by onyb** [comment]
@vgvassilev : Check the Travis CI builds of my fork on Linux and OSX platforms here: https://travis-ci.org/onyb/cling/builds/84894339

**Comment by vgvassilev** [comment]
Shall I merge #68 before merging this one?

**Comment by onyb** [comment]
@vgvassilev : No, don't merge #68 . You can close it later on (but without merging).

**Pull request merged**
