### PR TITLE
Fix #114 unresolved symbol bug in Jupyter

### LINKED ISSUE #114: Jupyter notebooks crash - unresolved symbol
Hi, thanks for fixing issue #113. Unfortunately jupyter notebooks are still not working. The error is the following:

```C++
IncrementalExecutor::executeFunction: symbol 'cling_runtime_internal_throwIfInvalidPointer' 
unresolved while linking [cling interface function]!
```
Please try the attached notebook in jupyter and you will see the error. 
This is with cling commit fbd11 and jupyter 4.2.0

[clingnotebook.zip](https://github.com/vgvassilev/cling/files/532047/clingnotebook.zip)

NOTE: the code works fine from the command line cling, the error only shows in the jupyter notebook.

### PR DESCRIPTION
**Pull request by erlanger**
This solves issue #114 under unix, don't know if the bug is present on Windows.

### CODE REVIEW

**Comment by erlanger** [comment]
Alright, travis tests are passing now I put some extra conditionals for APPLE builds.

**Comment by vgvassilev** [comment]
Merged. Thanks for your contribution.

**Comment by SylvainCorlay** [comment]
Awesome! Is this going to be on the nightly builds?

**Comment by erlanger** [comment]
@SylvainCorlay  I want to make a patch to be able to choose C++14 or C++11 from the jupyter web ui, but I have no clue about python traitlets. Can you point me to the code in the ipython kernel that I can use  as a base to learn how to use traitlets?

**Pull request closed without merging**
