### PR TITLE
Move to container based infrastructure in Travis CI

### PR DESCRIPTION
**Pull request by onyb**
This is a continuation of pull request #75 . I tested it on my fork, and seems to work. It might fail on your Travis account, since the ```LastKnownGoodLLVMSVNRevision.txt``` on this repo is outdated.

### CODE REVIEW

**Comment by vgvassilev** [comment]
I saw one failure and it is because of a missing patch in the branch cling-patches. I am waiting for the author to put it in and the PR could be integrated.

**Comment by vgvassilev** [comment]
I guess we will need https://github.com/vgvassilev/cling/commit/5c0692d847e623ee46e7ed47ba6ce39c5c922fc8 here...

**Comment by onyb** [comment]
@vgvassilev : Yes, https://github.com/vgvassilev/cling/commit/5c0692d847e623ee46e7ed47ba6ce39c5c922fc8 should be added. Meanwhile, I will add some more commits to this PR. After the ```cling-patches``` branch is fixed, also update these:
https://github.com/vgvassilev/llvm
and
https://github.com/vgvassilev/clang

**Comment by vgvassilev** [comment]
@onyb I've updated llvm.git and clang.git. I think the cling-patches branch should be fixed.

**Comment by vgvassilev** [comment]
@onyb We still need to find a way to use Travis... What about splitting into more steps. AFAIK they have a hard limit 2 hours per step.

**Comment by onyb** [comment]
@vgvassilev: The problem may not be due to the hard limit of 120 minutes per step. If you check the timestamps logged by CPT, it is evident that the builds fail due to some error, and is restarted a couple of times, because we used `travis_retry` (https://github.com/onyb/cling/commit/3680ba2dfea1f0d752de63ca5dd8be479164be89).  After doing this 2-3 times, the 120 minute hard limit stops the execution entirely.

To be able to split into steps, the scripts should be made modular, something which I have been wanting to do anyway. I will work on this in my fork, and open a new pull request with the changes. Hence, I am closing this one (#76).

**Pull request closed without merging**
